services:
  hashicorp.vault:
    image: ${DOCKER_REGISTRY-}hashicorp.vault:latest
    extra_hosts:
      - "vault.localhost:host-gateway"
    build:
      context: ./src
      dockerfile: Hashicorp.Vault/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_ENVIRONMENT: Development
    user: "1654:1654"
