apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-demo-app
  namespace: demo-app
spec:
  vaultAuthRef: vault-static-auth
  mount: kv-v2
  type: kv-v2
  path: demo-app/config
  refreshAfter: 10s
  destination:
    create: true
    name: config
  rolloutRestartTargets:
  - kind: Deployment
    name: demo-app

